### PR TITLE
(maint) Add ffi and minitar to shared project

### PR DESCRIPTION
**Pull request by donoghuc**
Acceptable versions of ffi and minitar have been added to the puppet-runtime project. This commit adds those to the project definition shared by puppet-bolt and pe-bolt-server.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I'm not sure why this makes sense. Shouldn't they just be part of the runtime? We shouldn't have to call them out explicitly.

**Comment by MikaelSmith** [comment]
Wouldn't this require adding back the component configs?

**Comment by MikaelSmith** [comment]
I suspect the problem is really that the puppet-agent version pe-bolt-server installs against doesn't have the updated runtime with ffi and minitar.

**Comment by donoghuc** [comment]
I see so the line https://github.com/puppetlabs/bolt-vanagon/blob/476379c72fcde9c0b5f31820cf0fa9dbf713dcfb/configs/projects/pe-bolt-server.rb#L3 requires puppet-agent which means that the packages in the corresponding agent-runtime https://github.com/puppetlabs/puppet-runtime/tree/master/configs/projects are available?

**Comment by MikaelSmith** [comment]
Yeah.

**Pull request closed without merging**
