### PR TITLE
(ORCH-2296) Remove pe-bolt-server

### PR DESCRIPTION
**Pull request by caseywilliams**
The pe-bolt-server project has moved to the dedicated
puppetlabs/pe-bolt-vanagon repo. This commit removes configs and
supporting files for it.

CI passed last night for pe-bolt-server packages built from the puppetlabs/pe-bolt-vanagon repo for all PE branches. I'll unblock this PR once I've successfully built this for all platforms.

### CODE REVIEW

**Comment by MikaelSmith** [comment]
Is this even necessary? The `johnson` branch specifically existed for pe-bolt-server.

**Comment by caseywilliams** [comment]
Oh, in that case I'll retarget this against master -- I assume we can get rid of the johnson branch now, then

**Comment by caseywilliams** [comment]
Ok, I've retargeted this and added a commit to update the gitignore for some vanagon metadata changes from somewhat recently. I'm building some packages now.

**Comment by caseywilliams** [comment]
[Here are successful builds](http://builds.puppetlabs.lan/puppet-bolt/d425ff66d94695c5b7c886fb27c637d4cf1d183b/artifacts/) of all platforms from nightly CI using these changes.

**Comment by donoghuc** [comment]
Thanks Casey. After this we can delete the johnson branch. Can we safely remove the `peversion` logic from platform definitions? https://github.com/caseywilliams/bolt-vanagon/blob/d425ff66d94695c5b7c886fb27c637d4cf1d183b/configs/platforms/ubuntu-18.04-amd64.rb#L1

**Comment by caseywilliams** [comment]
Oh gosh, yeah -- updated to remove those.

**Pull request merged**
